version: 4.0.2.{build}
image: Visual Studio 2017


environment:
  matrix:
  - PlatformToolset: v141

platform:
    - x64
    - Any CPU

configuration:
    - Release
    - Debug

install:
    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="Any CPU" set archi=x86
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %archi%

before_build:
  - nuget restore

build:
    parallel: true                  # enable MSBuild parallel builds
    verbosity: minimal

build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - msbuild WakaTime.sln /m /p:configuration="%configuration%" /p:platform="%platform%" /p:PlatformToolset="%PlatformToolset%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
    - cd "%APPVEYOR_BUILD_FOLDER%"\WakaTime
    - ps: >-

        if ($env:PLATFORM -eq "x64" -and $env:CONFIGURATION -eq "Release") {
            Push-AppveyorArtifact "obj\x64\$env:CONFIGURATION\WakaTime.dll" -FileName WakaTime.dll
        }

        if ($env:PLATFORM -eq "Any CPU" -and $env:CONFIGURATION -eq "Release") {
            Push-AppveyorArtifact "obj\$env:CONFIGURATION\WakaTime.dll" -FileName WakaTime.dll
        }

        if ($($env:APPVEYOR_REPO_TAG) -eq "true" -and $env:CONFIGURATION -eq "Release" -and $env:PLATFORMTOOLSET -eq "v141") {
            if($env:PLATFORM -eq "x64"){
            $ZipFileName = "notepadpp-wakatime_$($env:APPVEYOR_REPO_TAG_NAME)_x64.zip"
            Remove-Item obj\x64\$env:CONFIGURATION\*.exp
            Remove-Item obj\x64\$env:CONFIGURATION\*.lib
            7z a $ZipFileName obj\x64\$env:CONFIGURATION\*
            }
            if($env:PLATFORM -eq "Any CPU"){
            $ZipFileName = "notepadpp-wakatime_$($env:APPVEYOR_REPO_TAG_NAME)_x86.zip"
            Remove-Item obj\$env:CONFIGURATION\*.exp
            Remove-Item obj\$env:CONFIGURATION\*.lib
            7z a $ZipFileName obj\$env:CONFIGURATION\*
            }
        }

artifacts:
  - path: notepadpp-wakatime_*.zip
    name: releases
  - path: '**\WakaTime.dll'

deploy:
    provider: GitHub
    auth_token:
        secure: !!TODO, see https://www.appveyor.com/docs/deployment/github/#provider-settings!!
    artifact: releases
    draft: false
    prerelease: false
    force_update: true
    on:
        appveyor_repo_tag: true
        PlatformToolset: v141
        configuration: Release
